### ISSUE TITLE
Improvement ideas!

### ISSUE THREAD

**Issue by TheLearneer** [iuccio/csvToJson#16]
I was using this package for one of my project and recently got to know about some limitations and bugs in the package:

1. Boolean type is not parsed. _I even submitted a PR, but later realized it was not working as intended_
2. Number parsers is not accurate. _Empty string will also be parsed as number and results to 0_
3. Better identification for delimiter is required. 
  _if I have a field `,"how are you, I hope you are doing fine",0`_
  here the `,` inside the quotation is still regarded as delimiter.. so I guess **Support for quoted strings is needed**

Hope to see these changes happening..

**Comment by iuccio** [comment]
@TheLearneer 

the 1. and 2. points are now correctly implemented with the release [v1.0.2](https://github.com/iuccio/csvToJson/releases/tag/v1.0.2.)

About the 3. point: 
to be able to get the entire sentence, that includes the comma, you just need to change the field delimiter of your csv file. For example you can use the semi column (**;**) as field delimiter. After that in your source code, you have to use the following calls ([Define field delimiter](https://github.com/iuccio/csvToJson#define-field-delimiter)):

`csvToJson.fieldDelimiter(';').getJsonFromCsv(yourFile);`

**Comment by aataylor** [comment]
I came up against the issue #3 as well and found a way around it.  Looking at the source, it's doing  split() using the delimiter you pass in. Because of that, it's possible to specify regex as the delimiter and it works for my purposes. Perhaps that will for yours too. 


Regex I found on the internet: `,(?=(?:[^"]*"[^"]*")*[^"]*$)`

![image](https://user-images.githubusercontent.com/12817332/102653926-4fa1ad80-4135-11eb-8883-64edeecf581d.png)

using it with csvToJson: 
`csvToJson.fieldDelimiter(/,(?=(?:[^"]*"[^"]*")*[^"]*$)/).getJsonFromCsv(file);
`

**Comment by roberrrt-s** [comment]
@aataylor This works perfectly, thanks!
